### ISSUE TITLE
onScean方法空指针

### ISSUE THREAD

**Issue by icetea0822** [junkchen/BleLib#7]
您好，我的app有时候放在那里不动的时候，会报此错误，请问是什么原因啊

AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.junyuanrobot.aite, PID: 3863
                                                 java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.contains(java.lang.Object)' on a null object reference
                                                     at com.junkchen.blelib.BleService$2.onLeScan(BleService.java:468)
                                                     at android.bluetooth.BluetoothAdapter$2.onScanResult(BluetoothAdapter.java:1805)
                                                     at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:331)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5275)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)

**Comment by junkchen** [comment]
请使用这个版本 blelib-1.2.3 ，今天刚更新的。

**Comment by icetea0822** [comment]
scanLeDevice里面有个List的clear方法还是报错、、、、

**Comment by wutaodev** [comment]
@icetea0822   我也是报这个错，怎么解决啊？

**Comment by icetea0822** [comment]
当时好像自己写了，没有用作者的库了。

**Comment by wutaodev** [comment]
好吧，谢了
